export const CREATE_NOTE = 'CREATE_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const EDIT_NOTE = 'EDIT_NOTE'
export const VIEW_NOTE = 'VIEW_NOTE'
export const LOGIN_AUTH = 'LOGIN_AUTH'
export const SIGNUP_AUTH = 'SIGNUP_AUTH'
